
MNIST_IMG_ROWS = 28
MNIST_IMG_COLS = 28
MNIST_IMG_CHL = 1
MNIST_NUM_CLASSES = 10

CLASSIFIER_PATH = '../classifier'

PRETRAIN_CLASSIFIER_PATH = CLASSIFIER_PATH + '/pretrained_models'
MNIST_CNN_MODEL_WITH_PRE_SOFTMAX_FILE = '/MNIST_MODEl_WITH_PRE_SOFTMAX.h5'

SAVED_ATTACKER_PATH = './saved_models'
SAVED_IMAGE_SAMPLE_PATH = './saved_images'
SAVED_NPY_PATH = './saved_npy'
