client_config_backend: settings
client_config:
  client_id: 34250229279-ef4rnr9ba737uamp213r8m9nuh1plv0l.apps.googleusercontent.com
  client_secret: YJSqLmbAx_cDsFSIXwC-lu7o
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file

